name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Sync manifest version with tag
        run: node scripts/sync-version.mjs ${{ github.ref_name }}

      - name: Run tests
        run: yarn validate

      - name: Build extension
        run: yarn build

      - name: Create extension package
        run: |
          cd dist
          zip -r ../chromepass-extension-${{ github.ref_name }}.zip .
          cd ..

      - name: Determine previous tag
        id: prev_tag
        run: |
          current_tag="${GITHUB_REF_NAME}"
          # Find the previous tag by date, excluding current
          prev=$(git tag --sort=-creatordate | grep -v "^${current_tag}$" | sed -n '1p' || true)
          echo "tag=$prev" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: notes
        run: |
          if [ -n "${{ steps.prev_tag.outputs.tag }}" ]; then
            echo "body=See changes: https://github.com/${{ github.repository }}/compare/${{ steps.prev_tag.outputs.tag }}...${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "body=Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ChromePass ${{ github.ref_name }}
          body: ${{ steps.notes.outputs.body }}
          files: |
            ./chromepass-extension-${{ github.ref_name }}.zip
